version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1Qazxsw2!
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1Qazxsw2!
    ports:
      - 8082:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  unleash:
    image: unleashorg/unleash-server
    environment:
      - DATABASE_URL=postgres://postgres:1Qazxsw2!@postgres:5432/unleash
    restart: on-failure
    ports:
      - "4242:4242"
volumes:
  postgres-data:
  pgadmin: